update @actions/core to 1.10.0
seanmiddleditch/gha-setup-vsdevenv pull request #17
Opened 2023-01-25 15:41 UTC by compnerd

GitHub is working towards deprecating `set-output` in favour of a file based approach.  Update the `@actions/core` dependency to make avail of the new implementation which should hopefully eliminate the deprecation warning.

2023-01-25 15:42 UTC, compnerd commented
@seanmiddleditch I've recreated the PR (was originally #16) to rename the branch; I'm unsure if this project is now considered abandoned, but I've renamed the branch to allow others to use that as an alternate source to deal with the deprecation until we can sort out how to get this merged.

2023-10-25 19:53 UTC, seanmiddleditch requested changes

2023-10-25 19:53 UTC, seanmiddleditch commented on README.md
> +    - uses: compnerd/gha-setup-vsdevenv@main
Can you revert this change for the PR so it still points to this repo?

2023-10-25 19:53 UTC, seanmiddleditch commented on index.js
> +        '-nologo',
The first three args are the same as in `vswhereArgs`; perhaps a separate prefix list of common options should be defined?

2023-10-25 19:53 UTC, seanmiddleditch commented on index.js
> +      const details = spawn(vswherePath, args, { encoding: 'utf8' })
Perhaps just set the `stdio` args option to `[ 'ignore', 'inherit', 'inherit' ]` and then not bother with `details` ? That'll be more efficient (no buffering of input just to dump it back out to standard output), though that probably doesn't matter in any real way here.

2023-10-25 19:53 UTC, seanmiddleditch commented on index.js
> +        vsDevCmdArgs.push(`-vcvars_ver=${toolsetVersion}`)
Just to verify, is this a valid bugfix, or a new typo?

2023-10-25 19:53 UTC, seanmiddleditch commented on package.json
> +  "license": "MIT",
Please revert this; I do not want to require attribution for folks who fork/reuse code this trivial.

2023-10-25 19:53 UTC, seanmiddleditch commented
There's a few different changes here. I'd somewhat prefer them split out into separate PR, e.g. the `verbose` flag and any bug fixes.

(Repo isn't fully abandoned; I'm just not a very active maintainer, owning to not being paid to do this and trying to spend more time on non-computer-related hobbies.)

2023-10-25 19:55 UTC, compnerd commented
Ah, Thanks @seanmiddleditch! Sorry, I assumed that it was abandoned and starting making more changes. I can certainly split out most of them and send them back here if you are still interested.

2025-03-06 21:41 UTC, closed without merging